version: '3.9'

services:
  database:
    image: docker.io/mysql:8
    container_name: database-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vhf_opensky
    command:
      - '--binlog-expire-logs-seconds=3600'
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql

  flask-api:
    build: .
    image: app-image
    container_name: app-container
    environment:
      DATABASE_URL: mysql://root:root@database/vhf_opensky
    env_file:
      - deploy.env
    depends_on:
      - database
    links:
      - database
    ports:
      - 8000:8000

volumes:
  db-volume:
